# Generated by Django 6.0.6 on 2026-06-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('endpoint', models.CharField(default='/', help_text='Path on the device (e.g. /api/sensor)', max_length=200)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('data', models.TextField(blank=True, help_text='JSON body for POST/PUT requests')),
            ],
            options={
                'verbose_name': 'Device API',
                'verbose_name_plural': 'Device APIs',
            },
        ),
        migrations.RemoveField(
            model_name='device',
            name='endpoint',
        ),
        migrations.AddField(
            model_name='device',
            name='endpoints',
            field=models.ManyToManyField(blank=True, related_name='devices', to='main.deviceapi'),
        ),
    ]
