# Generated by Django 6.0.6 on 2026-07-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_private',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='is_semiprivate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
