# Generated by Django 6.0.6 on 2026-06-23 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_deviceapi_remove_device_endpoint_device_endpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='endpoints',
        ),
        migrations.DeleteModel(
            name='DeviceAPI',
        ),
    ]
