# Generated by Django 6.0.6 on 2026-07-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_device_is_private_device_is_semiprivate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_semiprivate',
            field=models.BooleanField(default=False),
        ),
    ]
