# Generated by Django 6.0.6 on 2026-07-16 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_device_creator_room_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objs', to='main.category'),
        ),
    ]
