# Generated by Django 6.0.6 on 2026-07-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_floor_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='devices',
            field=models.ManyToManyField(blank=True, null=True, related_name='rooms', to='main.device'),
        ),
    ]
